#### Pandas Practice Datset

In [ ]:
#Step 2: import Libraries
import  numpy as np
import pandas as pd

#### Usefulness of NumPy
for Math-heavy operations
AI model Training




#### Usefulness of Pandas
for Data manipulation like Dat clening e.t.c.
Data Management System

In [4]:
#Step 3:Load Dataset
df = pd.read_csv("data.csv")

df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [5]:
#Step 4: Explore the Dataset
display("Number of rows and columns using df.shape")
df.shape

display("The list of column names in a dataframe using df.columns")
df.columns

display("df.info() gives a structural summary of the dataframe")
df.info()

display("df.describe() generates a statistical summary of numerical column.")
df.describe()

'Number of rows and columns using df.shape'

'The list of column names in a dataframe using df.columns'

'df.info() gives a structural summary of the dataframe'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

'df.describe() generates a statistical summary of numerical column.'

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

#### Observations

1. From the df.shape we have 32 rows from 0 to 31
2. int 64 - Whole Numbers,float 64- Decimal numbers,object-Text(Strings) from the df.info()
3.Yes,the date is not meant to be an object like string won't be able to perform some manipulations on it well

In [11]:
# Step 5:NumPy Operations
array = np.array(df["Calories"])
display("Mean of calories Array:",np.mean(array))
display("Max of calories Array:",np.max(array))

display("Min of the calories Array:",np.min(array))

'Mean of calories Array:'

np.float64(nan)

'Max of calories Array:'

np.float64(nan)

'Min of the calories Array:'

np.float64(nan)

In [12]:
#Step 6: Missing Values Check

df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

1. Yes,there are missing values in date and calories,1 and 2 respectively.


2. Calories has the most

In [13]:
#Step 7:Simple Data Filtering

filtered_df = df[df["Calories"] > 300]
filtered_df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
4        45  '2020/12/05'    117       148     406.0
6        60  '2020/12/07'    110       136     374.0

Filter reserves rows based on a certain condition given and create a new dataset with the reserved data rows

#### Step 8:Reflection
1.Checking what the dataframe contain was easy just use df.head()

2. Difference between filtering and removing of missing values

3.How to Load raw data,filter data,perform numerical operations on data and alos how to Explore a Dataset